# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SSI_Inverts
                                 A QGIS plugin
 This plug-in attempts to build inverts for Surveying Solutions Inc
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-19
        copyright            : (C) 2018 by Cary Hutchinson Surveying Solutions Inc
        email                : chutchinson@ssi-mi.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SSI_Inverts class from file SSI_Inverts.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .invert_builder import SSI_Inverts
    return SSI_Inverts(iface)
